name: Main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: uv sync
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Build data
      run: uv run python -m pyvecorg build
      env:
        GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: Run tests
      run: uv run pytest -v
    - name: Build HTML
      run: uv run python -m pyvecorg freeze
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Deploy
      run: uv run python -m pyvecorg deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
