name: Main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Build data
      run: pipenv run build
      env:
        GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: Run tests
      run: pipenv run test -v
    - name: Build HTML
      run: pipenv run freeze
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Deploy
      run: pipenv run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
